fastq_chunks: 100 
paths:
  log: "logs"
  jobs: "jobs"
  submits: "submits"
  inputs: "inputs"
  tmp: "/scratch"
tasks_per_job:
  default: 1
  split-fastq: 1
  demultiplex: 10
  trim-galore: 10
  join-fastq-files: 1
  rna-map: 25
  int-demultiplex: 10
  int-demultiplex-rna-map: 25
slurm_options:
  extra-header-cmds: "" 
  # used if nothing else is specified
  default:
    time: "6:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
  # for fastq spliting 
  split-fastq:
    time: "04:00:00"
    cpus-per-task: 8
    mem-per-cpu: 64GB
  trim-galore:
    time: "04:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
  demultiplex:
    time: "04:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
  int-demultiplex:
    time: "12:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
  join-fastq-files:
    time: "12:00:00"
    cpus-per-task: 1
    mem-per-cpu: 4GB
  rna-map:
    time: "6:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
  rna-map-combine:
    time: "6:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
  int-demultiplex-rna-map:
    time: "2:00:00"
    cpus-per-task: 1
    mem-per-cpu: 2GB
